---
name: Getopt-Simple
version: 1.49
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: Provide a simple wrapper around Getopt::Long.
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Getopt::Long: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  Getopt::Simple:
    file: lib/Getopt/Simple.pm
    version: 1.49
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
