--- #YAML:1.0
name: Getopt-Simple
version: 1.47
author:
  - Ron Savage <ron@savage.net.au>
abstract: Provide a simple wrapper around Getopt::Long.
license: artistic
requires:
  Getopt::Long: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
